### ISSUE TITLE
How to ignore SSL certificate issues?

### ISSUE THREAD

**Issue by xantari** [serilog/serilog-sinks-email#137]
In code you can ignore certificate issues as indicated here: https://stackoverflow.com/questions/59199641/how-can-i-disable-server-certificate-validation-in-serilog-using-appsettings-jso

But there doesn't seem to be a way to do that in serilog email sink.

We need a way to bypass the SSL certificate issues...

Get this error when deal with invalid/self signed certificates:

2024-07-23T18:24:58.8610940Z BatchingSink (Serilog.Sinks.Email.EmailSink): failed emitting a batch during shutdown; dropping remaining queued events
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The host name (ex16-01.hwp.local) did not match any of the names given in the server's SSL certificate:
   *.xyz.com
   xyz.com

 ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(Boolean isAsync, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MailKit.Net.Smtp.SmtpClient.SslHandshake(SslStream ssl, String host, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.PostConnect(Stream stream, String host, Int32 port, SecureSocketOptions options, Boolean starttls, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.PostConnect(Stream stream, String host, Int32 port, SecureSocketOptions options, Boolean starttls, CancellationToken cancellationToken)
   at MailKit.Net.Smtp.SmtpClient.Connect(String host, Int32 port, SecureSocketOptions options, CancellationToken cancellationToken)
   at Serilog.Sinks.Email.MailKitEmailTransport.OpenConnectedSmtpClient()
   at Serilog.Sinks.Email.MailKitEmailTransport.SendMailAsync(EmailMessage emailMessage)
   at Serilog.Core.Sinks.Batching.BatchingSink.LoopAsync()

**Comment by xantari** [comment]
Figured it out.

```cs
        Log.Logger = new LoggerConfiguration()
                .MinimumLevel.Information() 
                .WriteTo.Console()
                .WriteTo.Email(new EmailSinkOptions()
                {
                    ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true,
                    Host = po.SmtpConfiguration.EmailServerAddress,
                    Port = po.SmtpConfiguration.EmailServerPort,
                    From = po.SmtpConfiguration.EmailFromAddress,
                    IsBodyHtml = true,
                    To = new List<string>() { po.SmtpConfiguration.ErrorOperatorEmail },
                    Subject = new Serilog.Formatting.Display.MessageTemplateTextFormatter("Subject TEST - " + argsFromMain),
                }, batchingOptions: new Serilog.Configuration.BatchingOptions()
                {
                    BufferingTimeLimit = TimeSpan.FromSeconds(30),
                    BatchSizeLimit = 1000
                }, restrictedToMinimumLevel: LogEventLevel.Error)
```
